name: bo_target
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26
  - scipy=1.11
  - matplotlib-base=3.10
  - pandas=2.3
  - scikit-learn=1.8
  - tqdm=4.67
  - openpyxl=3.1
  - joblib=1.5
  - c-compiler
  - cxx-compiler
  - pip
  - pip:
    - -e .
    - GPy==1.13.2
    - autograd==1.8.0
    - ultraplot==1.66.0
    - rdkit==2025.9.3
    - umap-learn==0.5.12
    - mordred==1.2.0
    - scikit-learn-extra==0.3.0
    - emukit @ git+https://github.com/sjiang87/emukit.git@0317f3189a0113aaca9842fcb8e111f89f78b412
    - pyDOE==0.3.8
